// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEVoPk-21mDwUhRcC-fJQpPT4RobNbeDY',
    appId: '1:313617588756:web:f56e86d314b7b33a4f7d01',
    messagingSenderId: '313617588756',
    projectId: 'celtic-sunlight-493102-t8',
    authDomain: 'celtic-sunlight-493102-t8.firebaseapp.com',
    storageBucket: 'celtic-sunlight-493102-t8.firebasestorage.app',
    measurementId: 'G-E1ZS077GHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7J7wJafHKdXyXPD3Q3FZtAU1K8-_57h0',
    appId: '1:313617588756:android:453dcfcca74340d14f7d01',
    messagingSenderId: '313617588756',
    projectId: 'celtic-sunlight-493102-t8',
    storageBucket: 'celtic-sunlight-493102-t8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm0LLGDAFK0OfPnQah2K75ppOBTIcdMm8',
    appId: '1:313617588756:ios:7c0172537bc357164f7d01',
    messagingSenderId: '313617588756',
    projectId: 'celtic-sunlight-493102-t8',
    storageBucket: 'celtic-sunlight-493102-t8.firebasestorage.app',
    iosBundleId: 'com.example.flameguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm0LLGDAFK0OfPnQah2K75ppOBTIcdMm8',
    appId: '1:313617588756:ios:7c0172537bc357164f7d01',
    messagingSenderId: '313617588756',
    projectId: 'celtic-sunlight-493102-t8',
    storageBucket: 'celtic-sunlight-493102-t8.firebasestorage.app',
    iosBundleId: 'com.example.flameguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEVoPk-21mDwUhRcC-fJQpPT4RobNbeDY',
    appId: '1:313617588756:web:7498cec26d3f52524f7d01',
    messagingSenderId: '313617588756',
    projectId: 'celtic-sunlight-493102-t8',
    authDomain: 'celtic-sunlight-493102-t8.firebaseapp.com',
    storageBucket: 'celtic-sunlight-493102-t8.firebasestorage.app',
    measurementId: 'G-W73GFX4EXM',
  );
}
